/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_LOG.h"
#include "Pin_LEDRED_aliases.h"
#include "Pin_LEDRED.h"
#include "Pin_LEDGREEN_aliases.h"
#include "Pin_LEDGREEN.h"
#include "Pin_LEDYELLOW_aliases.h"
#include "Pin_LEDYELLOW.h"
#include "SYSCOUNTER1.h"
#include "CLOCK1.h"
#include "isr_1msecTick.h"
#include "SYSCOUNTER2.h"
#include "CLOCK2.h"
#include "isr_2SecTick.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

